### ISSUE TITLE
src/uv_writer.c:370: UvWriterClose: Assertion `!w->closing' failed

### ISSUE THREAD

**Issue by tomponline** [canonical/raft#245] opened 2021-11-05 13:15 UTC
https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5139/arch=arm64,backend=dir,compiler=golang-1.16/console#console-section-5

```
/lxc-ci/build/tmp.KQmG1cbVOF/go/bin/lxc copy c1 c2 --refresh --instance-only --verbose
lxd: src/uv_writer.c:370: UvWriterClose: Assertion `!w->closing' failed.
Error: Put "http://unix.socket/1.0/instances/c2": EOF
```

**Comment by MathieuBordere** [comment] 2022-02-15 13:08
I hope https://github.com/canonical/raft/pull/265 fixes this one, if it doesn't occur in the lxd test suite for a while after this PR is merged, I will close this issue.

**Comment by MathieuBordere** [comment] 2022-02-15 15:56
This issue appeared before that PR, but the PR seems to make it occur more often (at least I was able to reproduce it, before I wasn't).

**Comment by freeekanayaka** [comment] 2022-02-15 16:06
Ah I see, good that the PR made it more evident then.

**Comment by MathieuBordere** [comment] 2022-04-26 12:42
@tomponline Have you seen this one since then?

**Comment by tomponline** [comment] 2022-04-26 12:48
Not that ive been aware of, but not been looking out for it particularly.

**Comment by MathieuBordere** [comment] 2022-04-28 13:15
Will close for now, happy to reopen if it pops up again.

**Closed by MathieuBordere** 2022-04-28 13:15 UTC
Labels: Bug
